import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
CubeMX_Config/Core/Src/stm32h7xx_hal_msp.c
''')

path = [cwd]
path += [cwd + '/CubeMX_Config/Core/Inc']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
