clean2:
	-$(RM) $(CC_DEPS)$(C++_DEPS)$(C_UPPER_DEPS)$(CXX_DEPS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS)
	-$(RM) $(OBJS) *.elf
	-@echo ' '


*.elf: $(wildcard F:/K-Forest/RTOS/RT-Thread/artpi-master/sdk-artpi-pr/sdk-bsp-stm32h750-realthread-artpi/projects/lrs007_lora_radio/board/linker_scripts/STM32H750XBHx/link.lds)
